name: hackaton-lifmat
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - aniso8601=9.0.1
  - attrs=23.1.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=41.0.3
  - dacite=1.8.1
  - flask=2.2.2
  - flask-cors=3.0.10
  - flask-restx=1.0.3
  - flask-sqlalchemy=3.0.2
  - greenlet=2.0.1
  - gunicorn=20.1.0
  - idna=3.4
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - krb5=1.20.1
  - llvm-openmp=14.0.6
  - markupsafe=2.1.1
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - pandas=2.1.1
  - pip=23.3
  - psycopg2=2.9.3
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - soupsieve=2.5
  - sqlalchemy=2.0.21
  - sqlite=3.41.2
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
